name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: [echo_message]
jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:      
      - name: Echo Message
        run: |
          echo -n '::add-mask::' > cmd.txt
          jq < ${GITHUB_EVENT_PATH} -r .client_payload.message >> cmd.txt
          cat cmd.txt
          rm cmd.txt
          echo ${{ github.event.client_payload.message }}
