name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: [echo_message]
jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:      
      - name: Add Mask
        run: |
          echo -n '::add-mask::' > cmd.txt
          jq < ${GITHUB_EVENT_PATH} -r .client_payload.message >> cmd.txt
          echo -n '::add-mask::' >> cmd.txt
          jq < ${GITHUB_EVENT_PATH} -r .client_payload.message2 >> cmd.txt
          cat cmd.txt
          rm cmd.txt

      - name: Echo Message
        run: |
          echo "${message}"
          echo "${message2}"
        env:
          message: ${{ github.event.client_payload.message }}
          message2: ${{ github.event.client_payload.message2 }}
